### ISSUE TITLE
如何合作开发

### ISSUE THREAD

**Issue by 1dot75cm** [910JQK/linuxbar#2]
贴吧轮子很赞， 请问可以贡献代码么？ @910JQK 

已经把该项目加入， [Flask resource index](https://repo.fdzh.org/blog/post/2) 了。

![](https://repo.fdzh.org/blog/api/v1.0/qrcode?url=https://repo.fdzh.org/blog/post/2&box_size=5&border=2&fcolor=121)

**Comment by 910JQK** [comment]
Feel free to contribute.
有人願意貢獻代碼當然好，我一個人也不知道猴年馬月才能寫完。

**Comment by 1dot75cm** [comment]
Thanks for reply. @910JQK 
窝也是刚刚才学着写 Flask，很多地方还不会。 明天窝看看该项目的源码。
