### ISSUE TITLE
轮子支持rss吗

### ISSUE THREAD

**Issue by lsblk** [910JQK/linuxbar#6]
贴吧本身不支持rss，，既然轮子可以做到用爬虫和贴吧同步，那也就可以加入rss订阅的功能，，测试的服务器已经下线了，，不知道支不支持呢，，支持的话忽略就好。。不支持希望可以加入，用rss实在是太方便了，，虽然回帖麻烦了点。。

**Comment by 910JQK** [comment]
很抱歉現在沒有精力繼續維護這個項目。
RSS 功能是沒有的，不過加上也並不困難，你若是感興趣的話不妨自己折騰一下。
實在抱歉……

**Comment by lsblk** [comment]
嗯嗯，，
